kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftp-claim
spec:
  storageClassName: manuel
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: ftp-volume
  selector:
    matchLabels:
      name: devops
